# Generated by Django 4.1.1 on 2022-09-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(blank=True, max_length=50, null=True, upload_to='images/')),
                ('company_size', models.CharField(choices=[('10-100', 'Small'), ('101-500', 'Medium'), ('501-1000', 'Large'), ('1000+', 'ExtraLarge')], max_length=10)),
            ],
        ),
    ]
